name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.0.0
      - name: Checkout submodules
        uses: actions/checkout@v4.0.0
        with:
          repository: zodac/advent-of-code-inputs
          token: ${{ secrets.SUBMODULE_ACCESS }}
          path: advent-of-code-inputs
      - name: Set up JDK
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.10.0
        with:
          distribution: 'temurin'
          java-version: '21'
          maven-version: '3.9.3'
      - name: Cache local .m2
        uses: actions/cache@v3.3.2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**.pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run lints and test with Maven
        run: mvn clean install -Dall
