name: Update README ⭐
on:
  push:

jobs:
  update-readme-2022:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 34827
          year: 2022
          tableMarker: <!--- advent_readme_stars_2022 --->
          sessionCookie: ${{ secrets.AOC_SESSION_COOKIE }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README stars for 2022
